### ISSUE TITLE
Remap vim-surround to z for vim-sneak consistency

### ISSUE THREAD

**Issue by LanHikari22** [mgarort/dotvim#1]
https://github.com/mgarort/dotvim/blob/e67260d70377c28a0d0a08d8f3733adb05d5d4bd/vimrc#L992

Hi there!

I couldn't see a quick example on how to configure vim-sneak to use 's' consistently even though it seems like a must-have, but I found a clear example in your vimrc so I made a [gist](https://gist.github.com/LanHikari22/6b568683d81cbb7a2252fac86f6f4a4b) for it so it's more easily accessible.

Thank you!

**Comment by mgarort** [comment]
Thanks to you! I agree it is a must have, so hopefully your gist will make it more visible. Unfortunately `g:surround_no_mappings` is not well documented.

Also, I originally took this from @ggandor , so kudos to him too!
